name: igym
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  design_system:
    path: lib/design_system

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: lib/design_system/fonts/Inter-Black.ttf
        - asset: lib/design_system/fonts/Inter-Bold.ttf
        - asset: lib/design_system/fonts/Inter-ExtraBold.ttf
        - asset: lib/design_system/fonts/Inter-Light.ttf
        - asset: lib/design_system/fonts/Inter-Medium.ttf
        - asset: lib/design_system/fonts/Inter-Regular.ttf
        - asset: lib/design_system/fonts/Inter-SemiBold.ttf
        - asset: lib/design_system/fonts/Inter-Thin.ttf
